import { type Stage, StageId } from '@/src/contexts/NavigationContext';

export type StageInteractionType =
  | 'choice-pills'
  | 'next-pill'
  | 'answer-options'
  | 'none';

export const stageInteractionType: Record<Stage, StageInteractionType> = {
  [StageId.Choice]: 'choice-pills',
  [StageId.Intro]: 'answer-options',
  [StageId.Evaluation]: 'none',
  [StageId.Explanation]: 'next-pill',
  [StageId.CharacterIncompatible]: 'none',
  [StageId.HistoricalIntro]: 'next-pill',
  [StageId.HistoricalSlavery]: 'next-pill',
  [StageId.HistoricalAuthoritarianism]: 'next-pill',
  [StageId.PersonalAccountability]: 'answer-options',
  [StageId.InjusticePersists]: 'none',
  [StageId.PersonalQuestion]: 'answer-options',
  [StageId.WouldYouLikeToBe]: 'answer-options',
  [StageId.RecognizingInjustice]: 'none',
  [StageId.BreakingQuestion]: 'answer-options',
  [StageId.StayComfortable]: 'none',
  [StageId.ApatheticStance]: 'none',
  [StageId.SpasaStory]: 'next-pill',
  [StageId.SpasaRevelation]: 'next-pill',
  [StageId.OtherPigs]: 'next-pill',
  [StageId.RootOfTheProblem]: 'next-pill',
  [StageId.AnimalsTreatedAsProducts]: 'next-pill',
  [StageId.LetThemLive]: 'answer-options',
  [StageId.AcceptingSelfOwnership]: 'answer-options',
  [StageId.DishonestSelfOwnership]: 'none',
  [StageId.FromTheWild]: 'next-pill',
  [StageId.ViciousCycle]: 'next-pill',
  [StageId.CowFate]: 'next-pill',
  [StageId.AnimalCostOfLiving]: 'next-pill',
  [StageId.ReproductionControl]: 'next-pill',
  [StageId.SolutionUse]: 'answer-options',
  [StageId.SolutionKnow]: 'answer-options',
  [StageId.VeganDietHealth]: 'answer-options',
  [StageId.AdditionalResources]: 'answer-options',
  [StageId.NotAcceptingHealth]: 'none',
  [StageId.SolutionChoice]: 'answer-options',
  [StageId.AddressingContradiction]: 'answer-options',
  [StageId.NotHonest]: 'none',
  [StageId.AlignBehaviour]: 'answer-options',
  [StageId.Excuse]: 'answer-options',
  [StageId.DoubleStandard]: 'answer-options',
  [StageId.NotThreatened]: 'none',
  [StageId.YouAreResponsible]: 'answer-options',
  [StageId.ActResponsibly]: 'answer-options',
  [StageId.NotWhoYouThink]: 'none',
  [StageId.AvoidingResponsibility]: 'none',
  [StageId.OkWithInjustice]: 'none',
  [StageId.VeganismPrinciple]: 'next-pill',
  [StageId.RighteousChoice]: 'next-pill',
  [StageId.CourageousChoice]: 'next-pill',
  [StageId.JoinUs]: 'none',
};
