import { type Stage, StageId } from '@/src/contexts/NavigationContext';
import {
  nextAfterAcceptingSelfOwnership,
  nextAfterAdditionalResources,
  nextAfterAlignBehaviour,
  nextAfterBreakingQuestion,
  nextAfterDaLiBiVoleo,
  nextAfterDoubleStandard,
  nextAfterExcuse,
  nextAfterKontradiktornostJe,
  nextAfterLetThemLive,
  nextAfterPersonalAccountability,
  nextAfterPersonalQuestion,
  nextAfterSolutionChoice,
  nextAfterSolutionKnow,
  nextAfterSolutionUse,
  nextAfterVecVeganski,
  nextAfterVeganDietHealth,
} from '@/src/lib/story/answerTransitions';

export const directStageTransitions: Partial<Record<Stage, Stage>> = {
  [StageId.RecognizingInjustice]: StageId.BreakingQuestion,
  [StageId.Intro]: StageId.Evaluation,
  [StageId.CharacterIncompatible]: StageId.Choice,
  [StageId.Explanation]: StageId.HistoricalIntro,
  [StageId.HistoricalIntro]: StageId.HistoricalSlavery,
  [StageId.HistoricalSlavery]: StageId.HistoricalAuthoritarianism,
  [StageId.HistoricalAuthoritarianism]: StageId.PersonalAccountability,
  [StageId.SpasaStory]: StageId.SpasaRevelation,
  [StageId.SpasaRevelation]: StageId.OtherPigs,
  [StageId.OtherPigs]: StageId.RootOfTheProblem,
  [StageId.RootOfTheProblem]: StageId.AnimalsTreatedAsProducts,
  [StageId.AnimalsTreatedAsProducts]: StageId.LetThemLive,
  [StageId.FromTheWild]: StageId.ReproductionControl,
  [StageId.ReproductionControl]: StageId.ViciousCycle,
  [StageId.ViciousCycle]: StageId.CowFate,
  [StageId.CowFate]: StageId.AnimalCostOfLiving,
  [StageId.AnimalCostOfLiving]: StageId.SolutionUse,
};

export const answerStageTransitions: Partial<
  Record<Stage, (answer: string) => Stage>
> = {
  [StageId.PersonalAccountability]: nextAfterPersonalAccountability,
  [StageId.PersonalQuestion]: nextAfterPersonalQuestion,
  [StageId.WouldYouLikeToBe]: nextAfterDaLiBiVoleo,
  [StageId.BreakingQuestion]: nextAfterBreakingQuestion,
  [StageId.LetThemLive]: nextAfterLetThemLive,
  [StageId.AcceptingSelfOwnership]: nextAfterAcceptingSelfOwnership,
  [StageId.SolutionUse]: nextAfterSolutionUse,
  [StageId.AlreadyVegan]: nextAfterVecVeganski,
  [StageId.SolutionKnow]: nextAfterSolutionKnow,
  [StageId.VeganDietHealth]: nextAfterVeganDietHealth,
  [StageId.AdditionalResources]: nextAfterAdditionalResources,
  [StageId.SolutionChoice]: nextAfterSolutionChoice,
  [StageId.AddressingContradiction]: nextAfterKontradiktornostJe,
  [StageId.AlignBehaviour]: nextAfterAlignBehaviour,
  [StageId.Excuse]: nextAfterExcuse,
  [StageId.DoubleStandard]: nextAfterDoubleStandard,
};
